language: python

install: source bootstrap.sh

script:
  - yes | vim +PlugUpdate +PlugSnapshot +w\ vim_plug_snapshot.txt +qa --startuptime vim_startuptime.txt && cat vim_startuptime.txt && cat vim_plug_snapshot.txt

notifications:
  email: false
