name: unit-tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  test:
    name: Unit tests
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Bootstrap
        run: source bootstrap.sh
      - name: Check vim version
        run: vim --version
      - name: Install vim plugins
        run: yes | vim +PlugUpdate +PlugSnapshot\ vim_plug_snapshot.txt +qa! && cat vim_plug_snapshot.txt
